import type { FeatureCollection } from 'geojson';
import type { Bar } from '../data/schema';

// Exact names in the border snapshots (after the label fixes), including labels that change across snapshots.
const POLITIES: Record<string, string[]> = {
  'kamakura-shogunate': ['Shogun Japan (Kamakura)'],
  'ashikaga-shogunate': ['Shogun Japan (Ashikaga)', 'Japan', 'Japan (Warring States)'],
  minoan: ['Minoan'], kerma: ['Kerma', 'Kush'], 'egypt-middle-kingdom': ['Egypt'], 'egypt-new-kingdom': ['Egypt'],
  andronovo: ['Andronovo'], 'late-harappan': ['Indus valley civilization'], xia: ['Xia'],
  'old-babylonian-period': ['Babylonia'], 'neo-babylonian': ['Neo-Babylonian Empire'],
  'hittite-empire': ['Hittites'], shang: ['Shang'], mycenaean: ['Greek city-states'], zhou: ['Zhou', 'Zhou states'],
  'vedic-period': ['Vedic Aryans'], olmec: ['Olmec'], kush: ['Kush', 'Meroe'], 'dong-son': ['Âu Lạc'],
  'neo-assyrian': ['Neo-Assyrian Empire'], chavin: ['Chavin'], scythians: ['Scythians', 'Proto-Scythian culture'],
  achaemenid: ['Achaemenid Empire'],
  'classical-greece': ['Greek city-states'], 'roman-republic': ['Roman Republic', 'Rome'],
  maurya: ['Mauryan Empire'], seleucid: ['Seleucid Kingdom'], 'ptolemaic-egypt': ['Ptolemaic Kingdom'],
  parthian: ['Parthia', 'Parthian Empire'], qin: ['Qin Empire'], xiongnu: ['Xiongnu', 'S. Xiongnu', 'Southern Xiongnu'],
  han: ['Han Empire', 'Han'], 'roman-empire': ['Roman Empire', 'Rome', 'Western Roman Empire', 'Eastern Roman Empire',
    'Rome (Constantinus)', 'Rome (Diocletianus)', 'Rome (Galerius)', 'Rome (Maximian)'],
  kushan: ['Kushan Empire', 'Kushan Principalities'], funan: ['Funan'], aksum: ['Axum'], moche: ['Moche'],
  'three-kingdoms': ['Wei', 'Shu', 'Wu'], sasanian: ['Sasanian Empire', 'Sasanian dependencies'],
  'classic-maya': ['Maya chiefdoms and states', 'Maya states', 'Maya city-states'], ghana: ['Empire of Ghana', 'Ghana'],
  gupta: ['Gupta Empire'], byzantine: ['Byzantine Empire', 'Eastern Roman Empire'],
  gokturk: ['Göktürks', 'Western Gokturk Khaganate'], sui: ['Sui Empire'], tiwanaku: ['Tiahuanaco Empire'], tang: ['Tang Empire'],
  rashidun: ['Rashidun Caliphate'], srivijaya: ['Srivijaya Empire'], umayyad: ['Umayyad Caliphate'],
  abbasid: ['Abbasid Caliphate'], heian: ['Japan', 'Yamato', 'Imperial Japan (Fujiwara)'],
  carolingian: ['Carolingian Empire'], khmer: ['Khmer Empire'], chola: ['Chola', 'Chola Empire', 'Cholas'],
  song: ['Song Empire'], 'holy-roman-empire': ['Holy Roman Empire'], seljuk: ['Seljuk Empire', 'Seljuk Caliphate'],
  'great-zimbabwe': ['Great Zimbabwe'],
  'mongol-empire': ['Mongol Empire', 'Great Khanate'], 'delhi-sultanate': ['Sultanate of Delhi'], mali: ['Mali'],
  'golden-horde': ['Golden Horde', 'Khanate of the Golden Horde'], mamluk: ['Mamluke Sultanate'], yuan: ['Yuan Empire', 'Great Khanate'],
  majapahit: ['Majapahit'], ottoman: ['Ottoman Empire', 'Ottoman Sultanate'], vijayanagara: ['Vijayanagara'],
  ming: ['Ming Empire', 'Ming Chinese Empire'], timurid: ['Timurid Empire', 'Timurid Emirates'], kongo: ['Congo'],
  joseon: ['Korea', 'Joseon'], aztec: ['Aztec Empire', 'Mexihcah (Triple Alliance)'], songhai: ['Songhai'],
  safavid: ['Safavid Empire'], 'new-spain': ['Viceroyalty of New Spain'], mughal: ['Mughal Empire'],
  'british-empire': ['England', 'England and Ireland', 'UK', 'United Kingdom', 'Great Britain',
    'United Kingdom of Great Britain and Ireland', 'British East India Company'],
  tokugawa: ['Tokugawa shogunate', 'Japan'], qing: ['Qing Empire', 'Manchu Empire'],
  'united-states': ['United States', 'United States of America'],
  'dutch-east-indies': ['Dutch East Indies', 'Netherlands Indies'],
  'british-raj': ['British Raj'], 'soviet-union': ['USSR'], prc: ['China'],
  gojoseon: ['Gojoseon'], goguryeo: ['Koguryo'], baekje: ['Paekche'], silla: ['Silla'], yamato: ['Yamato'],
  'jin-dynasty': ['Jin'], 'northern-wei': ['Toba Wei'], balhae: ['Parhae', 'Balhae'], liao: ['Liao'],
  'western-xia': ['Xixia'], 'jin-jurchen': ['Jin Empire'], goryeo: ['Korea', 'Goryeo'],
  'empire-of-japan': ['Imperial Japan', 'Empire of Japan'], 'republic-of-china': ['Republic of China', 'China'],
  manchukuo: ['Manchuria'], 'postwar-japan': ['Japan'], 'taiwan-roc': ['Taiwan'],
  'north-korea': ["Korea, Democratic People's Republic of"], 'south-korea': ['Korea, Republic of'],
  macedon: ['Empire of Alexander', 'Macedon and Hellenic League'], 'visigothic-kingdom': ['Visigoths', 'Visigothic Kingdom'],
  'frankish-kingdom': ['Franks', 'Frankish Kingdom'], 'republic-of-venice': ['Venice'],
  'al-andalus': ['Emirate of Córdoba', 'Caliphate of Córdoba'], 'papal-states': ['Papal States'],
  'kievan-rus': ['Kyivan Rus', 'Kievan Rus'], 'kingdom-of-england': ['England', 'England and Ireland'],
  'kingdom-of-france': ['Kingdom of France', 'France'], 'kingdom-of-hungary': ['Hungary', 'Kingdom of Hungary', 'Imperial Hungary'],
  muscovy: ['Grand Duchy of Moscow'], 'portuguese-empire': ['Portugal'], 'spanish-empire': ['Castile', 'Spain', 'Spanish Habsburg'],
  'habsburg-monarchy': ['Austrian Empire', 'Habsburg Monarchy', 'Habsburg Austria', 'Austria Hungary', 'Austro-Hungarian Empire'],
  'tsardom-of-russia': ['Tsardom of Muscovy'], 'polish-lithuanian-commonwealth': ['Poland-Lithuania', 'Polish–Lithuanian Commonwealth'],
  'dutch-republic': ['Dutch Republic'], 'swedish-empire': ['Sweden'], prussia: ['Prussia'],
  'russian-empire': ['Russian Empire', 'Russia'], 'first-french-empire': ['France'], 'german-empire': ['Germany', 'German Empire'],
  'nazi-germany': ['Germany'], 'israel-and-judah': ['Kingdom of Israel'], carthage: ['Carthaginian Empire', 'Carthage'],
  fatimid: ['Fatimid Caliphate'], ayyubid: ['Ayyubid Sultanate'], ilkhanate: ['Ilkhanate'], 'qajar-iran': ['Persia'],
  'pahlavi-iran': ['Persia', 'Iran'], 'republic-of-turkey': ['Turkey', 'Republic of Turkey'], israel: ['Israel'],
  'tibetan-empire': ['Tibetan Empire'], 'khazar-khaganate': ['Khazars'], 'uyghur-khaganate': ['Uyghurs'],
  ghaznavid: ['Ghaznavid Emirate'], 'chagatai-khanate': ['Chagatai Khanate'], 'northern-yuan': ['Northern Yuan'],
  'kazakh-khanate': ['Kazakh Khanate'], magadha: ['Magadha'], maratha: ['Maratha', 'Maratha Confederacy'],
  'sikh-empire': ['Sikhs', 'Sikh Empire'], india: ['India'], pakistan: ['Pakistan'],
  champa: ['Champa', 'Champa City States'], pagan: ['Pagan', 'Kingdom of Pagan', 'Pagan Kingdom'], 'dai-viet': ['Đại Việt', 'Annam'],
  ayutthaya: ['Ayutthaya'], 'malacca-sultanate': ['Malacca'], 'french-indochina': ['French Indochina', 'French Indo-China'],
  'kanem-bornu': ['Kanem', 'Kanem-Bornu'], benin: ['Benin'], 'ethiopian-empire': ['Ethiopia', 'Abyssinia'],
  asante: ['Asante'], zulu: ['Zululand', 'Zulu'],
};

export function territoryFor(geo: FeatureCollection, era: Pick<Bar, 'id' | 'title'>): FeatureCollection {
  const names = POLITIES[era.id] ?? [era.title];
  return {
    type: 'FeatureCollection',
    features: geo.features.filter((feature) =>
      names.includes(feature.properties?.NAME?.trim()) || names.includes(feature.properties?.SUBJECTO?.trim())),
  };
}
